[package]
edition = "2021"
name    = "simulation"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
device_query = "1.1.3"
winapi       = "0.3.9"
winput       = "0.2.5"
